migrate to 2021 edition
rust-lang/mdBook pull request #1831
Opened 2022-06-25 17:02 UTC by Dylan-DPC

* Moves to 2021 edition
* Removes `extern crate` for crates that were needed for macros, and replaced with imports in respective modules
* bumps msrv to 1.56.0 (version where edition was added)

2022-06-26 11:02 UTC, ISSOtm requested changes
These two fix the failing tests.

2022-07-31 01:23 UTC, mgeisler commented
Hey @Dylan-DPC, could you update the PR to fix the failing tests? I also wanted to bump the MSRV in #1866 so that I could play with edition 2021 dependencies in #1864.

2022-08-09 19:39 UTC, mgeisler commented
Anything I can do to help here? It seems @ISSOtm already debugged the failing tests, so it should be easy to fix.

2022-08-10 05:25 UTC, Dylan-DPC commented
Yeah i was busy with other projects so i didnt get the time to finish this. If you wish you can push a commit to my branch or I can look into it in a few days time hopefully

2022-08-15 08:47 UTC, mgeisler commented
> Yeah i was busy with other projects so i didnt get the time to finish this. If you wish you can push a commit to my branch or I can look into it in a few days time hopefully

Hi @Dylan-DPC, it's great to hear that you're still looking at it! I'm about to go on vacation for the rest of the week, so no hurry.

Note that I'm just a random guy, I'm not a maintainer or anything like that :-) I just (also) wants to see mdBook move to the new edition :-D

2022-09-09 09:25 UTC, mgeisler commented on src/config.rs
> +#[serde(rename_all = "kebab-case")]
Hi @ISSOtm, wow, thank you very much for debugging this! I wanted to fix the errors on the branch and this one made me scratch my head :smile:

2022-09-12 20:08 UTC, mgeisler commented
This was merged in https://github.com/rust-lang/mdBook/pull/1887.

2022-09-12 20:27 UTC, ehuss commented
Thanks, closing as resolved by #1887.

2022-09-12 20:27 UTC, closed without merging